- name: .vim dir
  file:
      path: "{{ ansible_env.HOME }}/.vim"
      state: directory

- name: .vim/autoload
  file:
      path: "{{ ansible_env.HOME }}/.vim/autoload"
      state: directory

- name: .vim/bundle
  file:
      path: "{{ ansible_env.HOME }}/.vim/bundle"
      state: directory

- name: download pathogen
  git:
      repo: https://github.com/tpope/vim-pathogen
      dest: /tmp/vim-pathogen

- name: copy pathogen into place
  copy:
      src: /tmp/vim-pathogen/autoload/pathogen.vim
      dest: "{{ ansible_env.HOME }}/.vim/autoload"
      remote_src: true
      
- name: install go support
  git:
      repo: 'https://github.com/fatih/vim-go.git'
      dest: "{{ ansible_env.HOME }}/.vim/bundle/vim-go"

- name: get airline
  git:
      repo: 'https://github.com/vim-airline/vim-airline.git'
      dest: "{{ ansible_env.HOME }}/.vim/bundle/vim-airline"

- name: get multi-cursor
  git:
      repo: 'https://github.com/terryma/vim-multiple-cursors.git'
      dest: "{{ ansible_env.HOME }}/.vim/bundle/vim-multiple-cursors"

- name: add .vimrc
  copy:
      src: "_vimrc"
      dest: "{{ ansible_env.HOME }}/.vimrc"
